### ISSUE TITLE
可以不删除而是选择移走吗？

### ISSUE THREAD

**Issue by Diadormu** [MSTnoin/gz_sweeper#2]
按目录结构移走，方便出了问题还原

**Comment by MSTnoin** [comment]
这个工具致力于简单。
而且小工具新增复原能力，会带来时序错误，让用户迷惑。
试想：
1、订阅MOD和鸽组汉化，看见汉化后仍是英文
2、找鸽组要说法，建议使用gz_sweeper
3、正常游玩
4、MOD更新，中文又变成英文，感到迷惑
5、没用清理而用复原功能，结果仍是英文，而且还出现了abcxxx.desc之类的键值丢失，更加迷惑
6、找鸽组要说法，建议重新订阅MOD
那你不如第一步就重新订阅MOD。
