### ISSUE TITLE
打扰了

### ISSUE THREAD

**Issue by TwilightMo0n** [MSTnoin/gz_sweeper#3]
您好，还请原谅我这个厚脸皮的人

其他p社游戏可以使用这个工具删除假中文吗，

如果可以的话能否请为我解惑呢。

十分感谢！

**Comment by MSTnoin** [comment]
我在代码里固定了stellaris的steam游戏编号，以及鸽组汉化模组编号。
也就是说，玩家在创意工坊订阅stellaris的各种模组，扫描这些模组，与鸽组汉化同名的文件才会被清理。
如果你需要清理其他P社游戏的假中文，需要汉化组把汉化文件都放在一个模组下，然后修改程序里的游戏编号和模组编号，最后手动运行这个程序。
结论：如果你不会编程，那么不能。

**Comment by 2653623401** [comment]
> 我在代码里固定了stellaris的steam游戏编号，以及鸽组汉化模组编号。 也就是说，玩家在创意工坊订阅stellaris的各种模组，扫描这些模组，与鸽组汉化同名的文件才会被清理。 如果你需要清理其他P社游戏的假中文，需要汉化组把汉化文件都放在一个模组下，然后修改程序里的游戏编号和模组编号，最后手动运行这个程序。 结论：如果你不会编程，那么不能。

您好，如果您允许的话我是否能够将改编自您的源码应用到p社其他游戏中。

**Comment by 2653623401** [comment]
> 我在代码里固定了stellaris的steam游戏编号，以及鸽组汉化模组编号。 也就是说，玩家在创意工坊订阅stellaris的各种模组，扫描这些模组，与鸽组汉化同名的文件才会被清理。 如果你需要清理其他P社游戏的假中文，需要汉化组把汉化文件都放在一个模组下，然后修改程序里的游戏编号和模组编号，最后手动运行这个程序。 结论：如果你不会编程，那么不能。

您好，如果您允许的话我是否能够将改编自您的源码应用到p社其他游戏中。

**Comment by 2653623401** [comment]
> 我在代码里固定了stellaris的steam游戏编号，以及鸽组汉化模组编号。 也就是说，玩家在创意工坊订阅stellaris的各种模组，扫描这些模组，与鸽组汉化同名的文件才会被清理。 如果你需要清理其他P社游戏的假中文，需要汉化组把汉化文件都放在一个模组下，然后修改程序里的游戏编号和模组编号，最后手动运行这个程序。 结论：如果你不会编程，那么不能。

您好，如果您允许的话我是否能够将改编自您的源码应用到p社其他游戏中。

我能否通过您的授权将此应用上传至创意工坊或是其他网站中。

当然我会将您以及鸽组的信息进行注明。

并且本人保证不会以鸽组的名义通过此源码获得任何货币收益。

还望您能进行批准。

**Comment by TwilightMo0n** [comment]
> 我在代码里固定了stellaris的steam游戏编号，以及鸽组汉化模组编号。 也就是说，玩家在创意工坊订阅stellaris的各种模组，扫描这些模组，与鸽组汉化同名的文件才会被清理。 如果你需要清理其他P社游戏的假中文，需要汉化组把汉化文件都放在一个模组下，然后修改程序里的游戏编号和模组编号，最后手动运行这个程序。 结论：如果你不会编程，那么不能。

您好，如果您允许的话我是否能够将改编自您的源码应用到p社其他游戏中。

我能否通过您的授权将此应用上传至创意工坊或是其他网站中。

当然我会将您以及鸽组的信息进行注明。

并且本人保证不会以鸽组的名义通过此源码获得任何货币收益。

当然，结果还是听从您的批准。

**Comment by TwilightMo0n** [comment]
再次叨扰

您好，如果您允许的话我是否能够将改编自您的源码应用到p社其他游戏中。

我能否通过您的授权将此应用上传至创意工坊或是其他网站中。

当然我会将您以及鸽组的信息进行注明。

并且本人保证不会以鸽组的名义通过此源码获得任何货币收益。

当然，结果我还是听从您的批准。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MSTnoin/gz_sweeper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月28日(星期一) 上午9:57
***@***.***&gt;;
抄送:&nbsp;"￼ 颐昔榠凡 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MSTnoin/gz_sweeper] 打扰了 (Issue #3)





 
我在代码里固定了stellaris的steam游戏编号，以及鸽组汉化模组编号。
 也就是说，玩家在创意工坊订阅stellaris的各种模组，扫描这些模组，与鸽组汉化同名的文件才会被清理。
 如果你需要清理其他P社游戏的假中文，需要汉化组把汉化文件都放在一个模组下，然后修改程序里的游戏编号和模组编号，最后手动运行这个程序。
 结论：如果你不会编程，那么不能。

**Comment by MSTnoin** [comment]
本工程开源且无商业利益。欢迎你使用本工程进行无商业利益的活动。注明信息即可。
