### ISSUE TITLE
功能请求：如果不在鸽组汉化同时又没有提供假中文的mod，提供创建假中文选项

### ISSUE THREAD

**Issue by RichardLuo0** [MSTnoin/gz_sweeper#4]
如果一个mod没有提供中文，同时又没有汉化，蠢驴会直接把他变成代码而不是回退到英文。
所以我希望直接给他创建一个假中文，这样至少还可以看看英文。

**Comment by MSTnoin** [comment]
各个mod提供的翻译文件本身是参差不齐的。

- 如果mod不含中文翻译文件，那么新增假中文很容易，但是，不能认定所有mod原语言都是英文。这可能需要对每个mod新增一个假语言选项。
- 程序不能简单地识别出mod提供的中文翻译是否为真正的中文翻译，还是假中文。
- 尽管逐个对比词条是最理想的，但mod作者词条格式错误的情况很多。正确的写法千篇一律，错误的写法各有各的错。始终有漏查和解析文件失败的风险。直接删掉与鸽组汉化重名的文件是最准确稳定的做法。
- 在先前的 issue #2 我解释了为什么mod提供的翻译文件不是被移走而是被直接删除。不想因为引入新功能而导致用户把误操作的压力给鸽组。

**Comment by MSTnoin** [comment]
我再补充一点，鸽组汉化在发布时，尚未翻译的词条是保留原文的。如果你进游戏后发现词条是缺失的，这证明在鸽组更新后，此mod又进行了更新且新增了词条。
